# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source "https://rubygems.org"

gem "sinatra", "~> 2.1"
gem "webrick", "~> 1.7"
gem "ffi", "~> 1.9"
gem "base64", "~> 0.2"
gem "abbrev", "~> 0.1.0"
gem "bigdecimal", "~> 3.1.8"
gem "csv", "~> 3.2.6"
gem "drb", "~> 2.2.0"
gem "getoptlong", "~> 0.2.0"
gem "mutex_m", "~> 0.2.0"
gem "nkf", "~> 0.4.0"
gem "observer", "~> 0.1.2"
gem "resolv-replace", "~> 0.1.0"
gem "rinda", "~> 0.2.0"
gem "syslog", "~> 0.1.0"
