# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source 'https://rubygems.org'

# Rack 3 is the standard for Ruby 3.2+ and 4.0
# Rackup was moved out of rack in Rack 3.0
gem "rack", "~> 3.0"
gem "rackup", "~> 2.3.1"
# Mustermann 3.0+ is required for modern Ruby compatibility
gem "mustermann", "~> 3.0"
# Webrick and ostruct are required as a standalone gem now
gem "webrick", "~> 1.8"
gem "ostruct", "~> 0.6"
gem "logger"
