source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

gem "minitest", ">= 5.25.6"

# Rails 7.1+ is much more stable on Ruby 4.0 than 7.0.x
gem "rails", "~> 7.1.0"

# Use the latest Sprockets for Ruby 4 compatibility
gem "sprockets-rails", "~> 3.4"

# Puma 6+ is required for Ruby 4.0's new thread management
gem "puma", "~> 6.4"

# Windows support
gem "tzinfo-data", platforms: %i[ mingw mswin x64_mingw jruby ]

gem "sqlite3", "~> 1.7"

# Rails will crash during boot without these explicit gems (Ruby 4.0)
gem "logger", "~> 1.6"
gem "base64", "~> 0.2"
gem "mutex_m", "~> 0.3.0"
gem "bigdecimal", "~> 3.1"
gem "ostruct", "~> 0.6"
gem "drb", "~> 2.2"
gem "net-smtp", "~> 0.5.0"
gem "concurrent-ruby", "1.3.4"
gem "psych", "~> 5.0"

group :development do
  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end