load("@io_bazel_rules_go//go:def.bzl", "go_library", "go_test")

go_library(
    name = "static",
    srcs = [
        "firebase.go",
        "glob.go",
        "static.go",
    ],
    importpath = "github.com/GoogleCloudPlatform/buildpacks/" + package_name(),
    visibility = [
        "//:__subpackages__",
    ],
)

go_test(
    name = "static_test",
    srcs = [
        "firebase_test.go",
        "static_test.go",
    ],
    data = glob(["testdata/**"]),
    embed = [":static"],
    rundir = ".",
    deps = [
        "//pkg/testdata",
        "@com_github_google_go-cmp//cmp:go_default_library",
    ],
)
