# Copyright 2020 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

source "https://rubygems.org"

# Sinatra 3.x requires Rack 2.x
gem "sinatra", "~> 3.0"

# Rackup 1.x is the version that works with Rack 2.x
gem "rackup", "~> 1.0"

# Puma 7 is fine as it supports both Rack 2 and 3
gem "puma", "~> 7.2"

# Ruby 4.0 compatibility gems
gem "logger", "~> 1.6"
gem "webrick", "~> 1.8"
gem "base64", "~> 0.2"
gem "ostruct", "~> 0.6"
